### ISSUE TITLE
When is the Release Date?

### ISSUE THREAD

**Issue by autowert66** [hobrin/Seed-Overlay#1]
When is the official release date? And can the public use Alpha / Beta Versions?

**Comment by hobrin** [comment]
Probably once a big client has seed overlay I will publish my mod, so <b>basically no for the time being</b>. The core reason why it is not public yet is because of the fact that it is less useful if everyone has it. I can provide it on request via discord though.

**Comment by autowert66** [comment]
Can you add the Discord Link to the description?

**Comment by hobrin** [comment]
Ok, I will link the BarrenDome discord with seed overlay to the description. Is that what you meant?

**Comment by autowert66** [comment]
> Ok, I will link the BarrenDome discord with seed overlay to the description. Is that what you meant?
Yes thank you.
🤗
